name: CI via GitHub Actions

on:
  push:
    tags: [ '*.*.*' ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: swift test -c release -Xswiftc -enable-testing -v
